### ISSUE TITLE
Add a remind-me command

### ISSUE THREAD

**Issue by BryanSLam** [BryanSLam/discord-bot#10]
There are times where stocks need time to fall or you want to check back 2 weeks before a stocks earnings, add some way to track reminders and store alerts either in-memory or using S3 to prop up reminders when they happen

**Comment by nickyhuynh** [comment]
i'm on it boss

**Comment by BryanSLam** [comment]
I'm already working on it

**Comment by BryanSLam** [comment]
DONE
