### ISSUE TITLE
Fix logs, theyre so fucking ugly

### ISSUE THREAD

**Issue by BryanSLam** [BryanSLam/discord-bot#33]
![screen shot 2018-09-25 at 1 59 01 pm](https://user-images.githubusercontent.com/2328845/46042818-32ebac00-c0cb-11e8-8028-f129e2a228d9.png)

**Comment by BryanSLam** [comment]
One line and leave the log type either on the same line, or remove it since we're doing colors anyways

**Comment by jonwho** [comment]
not true they're beautiful

FKU BIGBOI

**Comment by jonwho** [comment]
also add timestamps in front `# [10:10:10 INFO] w/e logging sttmt`

**Comment by jonwho** [comment]
hey merge my pr

**Comment by BryanSLam** [comment]
its already deployed you fuck
